import {useMemo,useState} from "react";
import {Activity,AlertTriangle,ArrowUpRight,CalendarDays,CheckCircle2,CircleHelp,Compass,Search,ShieldCheck,SlidersHorizontal} from "lucide-react";
import {filterOpportunities,opportunities,type Evaluation,type Opportunity} from "./domain";
type Section="Overview"|"Opportunities"|"Action Preview"|"Events"|"My Activity"|"Safety & Alerts";
const sections:{label:Section;icon:typeof Compass}[]=[{label:"Overview",icon:Compass},{label:"Opportunities",icon:Search},{label:"Action Preview",icon:SlidersHorizontal},{label:"Events",icon:CalendarDays},{label:"My Activity",icon:Activity},{label:"Safety & Alerts",icon:ShieldCheck}];
const labels:Array<Evaluation|"All">=["All","Worth researching","Proceed with caution","Avoid"];
export default function App(){const[section,setSection]=useState<Section>("Overview");const[query,setQuery]=useState("");const[evaluation,setEvaluation]=useState<Evaluation|"All">("All");const[tasks,setTasks]=useState<string[]>([]);const filtered=useMemo(()=>filterOpportunities(opportunities,query,evaluation),[query,evaluation]);return <div className="shell"><aside className="sidebar"><button className="brand" onClick={()=>setSection("Overview")}><span className="brand-mark">D</span><span><strong>dropchoice</strong><small>RESEARCH WORKSPACE</small></span></button><div className="nav-label">WORKSPACE</div><nav aria-label="Main navigation">{sections.map(({label,icon:Icon})=><button key={label} className={section===label?"nav-item active":"nav-item"} onClick={()=>setSection(label)}><Icon size={17}/>{label}</button>)}</nav><div className="sidebar-foot"><span className="status-dot"/> LOCAL DEMO <span className="version">v0.1</span></div></aside><main className="main"><header className="topbar"><span><span className="eyebrow">XIRRAEN / PROJECTS</span><b>Dropchoice / {section}</b></span><span className="local-pill"><span className="status-dot"/> Demo environment</span></header><div className="content"><div className="safety-banner"><ShieldCheck size={18}/><div><strong>Research prototype — demo data only</strong><p>No wallet is connected. No signature is requested. No transaction can be executed from this prototype. Verify official sources yourself.</p></div></div>
{section==="Overview"&&<><PageHeading eyebrow="EVIDENCE FIRST · UNCERTAINTY VISIBLE" title="Make research more deliberate." text="Collect signals, inspect evidence, and decide what deserves further investigation."/><div className="stats-grid"><Stat label="Sample opportunities" value={String(opportunities.length).padStart(2,"0")} note="Demo records only"/><Stat label="Needs caution" value={String(opportunities.filter(o=>o.evaluation==="Proceed with caution").length).padStart(2,"0")} note="Not a risk guarantee"/><Stat label="Verified live sources" value="00" note="No live ingestion"/><Stat label="Tasks completed" value={String(tasks.length).padStart(2,"0")} note="Current page state"/></div><section className="section-block"><div className="section-title"><div><span className="eyebrow">RESEARCH QUEUE</span><h2>Opportunity signals</h2></div><button className="text-button" onClick={()=>setSection("Opportunities")}>View all <ArrowUpRight size={15}/></button></div><OpportunityList items={filtered.slice(0,3)}/></section><section className="section-block route-card"><span className="eyebrow">READ-ONLY COMPARISON</span><h2>Preview trade-offs before taking action.</h2><p>Compare effort, unknowns, and safety constraints. This preview never connects a wallet or submits a transaction.</p><button className="primary-button" onClick={()=>setSection("Action Preview")}>Open Action Preview <ArrowUpRight size={16}/></button></section></>}
{section==="Opportunities"&&<><PageHeading eyebrow="SIGNALS / RESEARCH RECORDS" title="Opportunities" text="Every record is demo content until a verifiable source is attached."/><div className="filters"><label className="search-box"><Search size={17}/><input value={query} onChange={e=>setQuery(e.target.value)} placeholder="Search records..." aria-label="Search opportunities"/></label><label className="select-wrap"><span className="sr-only">Filter by evaluation</span><select value={evaluation} onChange={e=>setEvaluation(e.target.value as Evaluation|"All")}>{labels.map(x=><option key={x}>{x}</option>)}</select></label></div><OpportunityList items={filtered}/></>}
{section==="Action Preview"&&<><PageHeading eyebrow="ROUTE TRADE-OFFS" title="Action Preview" text="Compare assumptions, effort, and unknowns. This page is read-only."/><div className="preview-grid"><Preview title="Route A · Research first" effort="Medium" cost="Unknown" detail="Review official docs, eligibility rules, and contract provenance before considering participation."/><Preview title="Route B · Participate later" effort="High" cost="Network fees may apply" detail="Defer participation until source verification and risk review are complete."/></div><Notice text="This is not a transaction builder, quote engine, wallet connector, or execution interface. No route can be submitted."/></>}
{section==="Events"&&<><PageHeading eyebrow="CALENDAR CONTEXT" title="Events" text="Event and deadline tracking requires verified sources before production."/><Empty title="No verified events" text="There is no live event feed in this prototype. Do not infer deadlines or eligibility."/></>}
{section==="My Activity"&&<><PageHeading eyebrow="PERSONAL RESEARCH" title="My Activity" text="Checklist state exists only in this page session and is not persisted."/><div className="task-list">{["Inspect an official project source","Record unknown costs and requirements","Check contract and domain provenance"].map(task=><label className="task-row" key={task}><input type="checkbox" checked={tasks.includes(task)} onChange={()=>setTasks(cur=>cur.includes(task)?cur.filter(x=>x!==task):[...cur,task])}/><span><strong>{task}</strong><small>Research checklist · local state only</small></span>{tasks.includes(task)&&<CheckCircle2 size={18}/>}</label>)}</div></>}
{section==="Safety & Alerts"&&<><PageHeading eyebrow="RISK CONTEXT" title="Safety & Alerts" text="Clear boundaries are part of the product, not a footnote."/><div className="preview-grid"><Safety title="No wallet access" text="This prototype does not connect to wallets or request signatures."/><Safety title="No live Web Scan" text="No URLs are fetched; scan behavior is not connected to the network."/><Safety title="Evidence is incomplete" text="Sample records are not verified recommendations. Inspect official sources independently."/></div></>}
</div></main></div>}
function PageHeading({eyebrow,title,text}:{eyebrow:string;title:string;text:string}){return <div className="page-heading"><span className="eyebrow">{eyebrow}</span><h1>{title}</h1><p>{text}</p></div>}
function Stat({label,value,note}:{label:string;value:string;note:string}){return <article className="stat-card"><span>{label}</span><strong>{value}</strong><small>{note}</small></article>}
function OpportunityList({items}:{items:Opportunity[]}){return items.length?<div className="opportunity-list">{items.map(item=><article className="opportunity-card" key={item.id}><div className="opportunity-icon"><Compass size={19}/></div><div className="opportunity-body"><div className="opportunity-meta">{item.ecosystem} · {item.category}</div><h3>{item.name}</h3><p>{item.summary}</p><div className="evidence-line">{item.evidence[0]}</div>{item.risk&&<div className="risk-line"><AlertTriangle size={14}/>{item.risk}</div>}</div><div className="opportunity-side"><span className={"evaluation "+(item.evaluation==="Avoid"?"avoid":item.evaluation==="Proceed with caution"?"caution":"research")}>{item.evaluation}</span><span className="confidence">{item.confidence}%<small>demo confidence</small></span><span className="effort">{item.effort} effort</span></div></article>)}</div>:<Empty title="No matching records" text="Try a different query or evaluation filter."/>}
function Preview({title,effort,cost,detail}:{title:string;effort:string;cost:string;detail:string}){return <article className="preview-card"><span className="eyebrow">HYPOTHETICAL ROUTE</span><h2>{title}</h2><p>{detail}</p><div className="preview-metrics"><div><small>Estimated effort</small><strong>{effort}</strong></div><div><small>Estimated cost</small><strong>{cost}</strong></div></div><span className="readonly"><ShieldCheck size={14}/> Read-only · no execution</span></article>}
function Safety({title,text}:{title:string;text:string}){return <article className="preview-card"><ShieldCheck size={20}/><h2>{title}</h2><p>{text}</p></article>}
function Notice({text}:{text:string}){return <div className="notice"><CircleHelp size={18}/><p>{text}</p></div>}
function Empty({title,text}:{title:string;text:string}){return <div className="empty-state"><CircleHelp size={22}/><strong>{title}</strong><p>{text}</p></div>}
